### ISSUE TITLE
PSR Support

### ISSUE THREAD

**Issue by Faryshta** [LRotherfield/Nibble-Forms#1]
Some of the classes (including the main class) doesn't support PSR completely.

**Comment by LRotherfield** [comment]
Thanks for pointing that out, I will try and get this rectified over the weekend.

**Comment by Faryshta** [comment]
I can help if you want.

**Comment by LRotherfield** [comment]
I am going to try http://cs.sensiolabs.org/ I will update on how I get on, thanks for the offer, I may take you up on it

**Comment by LRotherfield** [comment]
I have run the cs fixer and checked over and made a few updates, I have also been reading the PSR 1 and 2 guidelines, its a big job.

**Comment by Faryshta** [comment]
I know, but its worth it.

Now that library can be used easier in other projects (which is why I started the issue actually :smile: )

**Comment by LRotherfield** [comment]
I need to go to bed now, I will re-read the specs and try and update the remaining issues this weekend.  If you can note any obvious issues that would be great.  Thanks for your help

**Comment by Faryshta** [comment]
A view notes on this class
https://github.com/LRotherfield/Nibble-Forms/blob/master/NibbleForm.class.php

1) line 565 its executing something and you have to separate declarations
from executions on different files.

2) line 567 you can't declare more than one class per file.

3) The fully-qualified namespace and class is suffixed with .php when
loading from the file system.

But the most important

4) Each namespace must have a top-level namespace ("Vendor Name") The
vendor name can be anything you want it to be, for example LRotherfield

There are several lines that are longer than 80 characters but that is not
a violation, just a recommendation so I don't think that needs to be fixed.

Good day and good work

**Comment by Faryshta** [comment]
I noticed you have a nibble framework with other components. Then you might want to name your "Vendor Namespace" Nibble :+1:

**Comment by LRotherfield** [comment]
I have started to sort the issues you named above.  The namespaces and file names should now be correct.  Would you mind quickly checking?

**Comment by Faryshta** [comment]
I checked every class and looks very much correct :+1:

In my opinion you can close this issue with peace of mind. The class is now PSR compliant AFAIK

**Comment by Faryshta** [comment]
If I might make a suggestion the class `Nibble\NibbleForms\Field\FormField` can be renamed to `Nibble\NibbleForms\Field` and still be PSR compliant (as long as you put it in the proper folder with the proper name).

It will be a bit easier to understand because that way the Nibble\NibbleForms\Field namespaces will be for classes extending the abstract Field class

**Comment by LRotherfield** [comment]
Thanks for your help

**Comment by Faryshta** [comment]
Thanks to you for taking time to fix this. And congrats for your work
