### ISSUE TITLE
Bug whith CheckBox

### ISSUE THREAD

**Issue by RobinDev** [LRotherfield/Nibble-Forms#2]
When you valid a form with 0 checked checkbox, there is the warning "Invalid argument supplied for foreach()"... So i just added a is_array (In the MultipleOptions file) : 

``` php
public function validate($val)
    {
        if (is_array($val)) {
            if ($this->minimum_selected && count($val) < $this->minimum_selected) {
                $this->error[] = sprintf('at least %s options must be selected', $this->minimum_selected);
            }
        } elseif ($this->required) {
            $this->error[] = 'is required';
        }
        if(is_array($val)) {
            foreach ($val as $answer) {
                if (in_array($answer, $this->false_values)) {
                    $this->error[] = "$answer is not a valid choice";
                }
            }
        }

        return !empty($this->error) ? false : true;
    }
```

**Comment by LRotherfield** [comment]
Hi Robin, thanks for this, if you open a pull request I will bring this across.

**Comment by LRotherfield** [comment]
In fact, it would be better to move the foreach into the above if statement that way there is no repetition

**Comment by RobinDev** [comment]
"In fact, it would be better to move the foreach into the above if statement that way there is no repetition"
Yes !

"Hi Robin, thanks for this, if you open a pull request I will bring this across."
Ok, I'm not yet familiar with Github that's why i open an issue.

**Comment by LRotherfield** [comment]
This should be fixed in this commit https://github.com/LRotherfield/Nibble-Forms/commit/a990001eddff2b53903c4097d892357404560d2e if it works for you, please let me know so I can close this.  Cheers
